# Generated by Django 6.0.4 on 2026-04-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=512)),
                ('spotify_url', models.CharField(blank=True, max_length=512)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('followers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('album_type', models.CharField(max_length=32)),
                ('uri', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=512)),
                ('spotify_url', models.CharField(blank=True, max_length=512)),
                ('release_date', models.CharField(max_length=32)),
                ('release_date_precision', models.CharField(max_length=16)),
                ('total_tracks', models.IntegerField()),
                ('artists', models.ManyToManyField(blank=True, related_name='albums', to='spotify.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('uri', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=512)),
                ('spotify_url', models.CharField(blank=True, max_length=512)),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField(default=False)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('track_number', models.IntegerField()),
                ('disc_number', models.IntegerField(default=1)),
                ('is_local', models.BooleanField(default=False)),
                ('is_playable', models.BooleanField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='spotify.album')),
                ('artists', models.ManyToManyField(blank=True, related_name='tracks', to='spotify.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SavedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField()),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='spotify.track')),
            ],
        ),
    ]
