# Generated by Django 6.0.4 on 2026-04-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifytoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.FloatField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('key', models.IntegerField()),
                ('liveness', models.FloatField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('tempo', models.FloatField()),
                ('time_signature', models.IntegerField()),
                ('valence', models.FloatField()),
                ('analysis_url', models.CharField(blank=True, max_length=512)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_features', to='spotify.track')),
            ],
        ),
    ]
