# Generated by Django 6.0.4 on 2026-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_add_audio_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(choices=[('user', 'Authorization Code (user)'), ('client', 'Client Credentials (app-only)')], default='user', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
