# Generated by Django 6.0.4 on 2026-04-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_spotifytoken_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(blank=True, null=True)),
                ('collaborative', models.BooleanField(default=False)),
                ('snapshot_id', models.CharField(blank=True, max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255)),
                ('href', models.CharField(blank=True, max_length=512)),
                ('spotify_url', models.CharField(blank=True, max_length=512)),
                ('owner_id', models.CharField(blank=True, max_length=255)),
                ('owner_display_name', models.CharField(blank=True, max_length=255)),
                ('total_tracks', models.IntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=64)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='spotify.playlist')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlist_tracks', to='spotify.track')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist', 'position')},
            },
        ),
    ]
