# Generated by Django 6.0.4 on 2026-04-13 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_playlist_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackLyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumental', models.BooleanField(default=False)),
                ('plain_lyrics', models.TextField(blank=True)),
                ('synced_lyrics', models.TextField(blank=True, help_text='LRC-format time-synced lyrics.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='spotify.track')),
            ],
        ),
    ]
