# Generated by Django 6.0.4 on 2026-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_add_track_lyrics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_stale',
            field=models.BooleanField(default=False, help_text='True when snapshot_id has changed but tracks have not yet been re-synced.'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks_synced_at',
            field=models.DateTimeField(blank=True, help_text='When tracks were last successfully delta-synced for this playlist.', null=True),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='position',
            field=models.IntegerField(db_index=True),
        ),
    ]
