# Generated by Django 6.0.4 on 2026-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_playlist_staleness_and_playlisttrack_position_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='ignored',
            field=models.BooleanField(blank=True, default=None, help_text='True when the user explicitly excluded this playlist from future syncs.', null=True),
        ),
    ]
