# Generated by Django 6.0.4 on 2026-04-13 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify', '0009_playlist_staleness_and_playlisttrack_position_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vader_positive', models.FloatField()),
                ('vader_negative', models.FloatField()),
                ('vader_neutral', models.FloatField()),
                ('vader_compound', models.FloatField()),
                ('classifier_label', models.CharField(blank=True, max_length=64)),
                ('classifier_score', models.FloatField(null=True)),
                ('classifier_model', models.CharField(blank=True, max_length=128)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='spotify.track')),
            ],
        ),
        migrations.CreateModel(
            name='LyricEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('dimensions', models.IntegerField()),
                ('embedding', models.BinaryField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_embeddings', to='spotify.track')),
            ],
            options={
                'unique_together': {('track', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='TrackFeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('feature_spec', models.JSONField()),
                ('dimensions', models.IntegerField()),
                ('vector', models.BinaryField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_vectors', to='spotify.track')),
            ],
            options={
                'unique_together': {('track', 'version')},
            },
        ),
    ]
