# Generated by Django 6.0.4 on 2026-07-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_mashuppair'),
        ('spotify', '0009_playlist_staleness_and_playlisttrack_position_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashuppair',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TrackTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('tags', models.JSONField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tags', to='spotify.track')),
            ],
            options={
                'unique_together': {('track', 'model_name')},
            },
        ),
    ]
