# Generated by Django 6.0.4 on 2026-07-03 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_add_track_tags'),
        ('spotify', '0009_playlist_staleness_and_playlisttrack_position_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracktags',
            name='vocab_hash',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.CreateModel(
            name='TagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('model_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='spotify.track')),
            ],
            options={
                'unique_together': {('track', 'axis', 'tag')},
            },
        ),
    ]
